# This is a basic workflow to help you get started with Actions

name: Auto Assign Action

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: kentaro-m/auto-assign-action@v1.1.0
      with:
       # A token for the repo
       repo-token: "${{ secrets.GITHUB_TOKEN }}"
       # A path for the auto-assign configuration
       configuration-path: ".github/auto_assign.yml"
